### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by includealex** [objectionary/eo-strings#108]
As there were implemented list of things we wanted, we release should come (we need those methods in other repositories for working with text matchers).

**Comment by includealex** [comment]
@yegor256 @Graur what do you think about it?

**Comment by Graur** [comment]
@includealex @yegor256 The last release was on 15 of September. So, I believe it's time to release `eo-srtings`

**Comment by yegor256** [comment]
@rultor release, tag is `0.1.0`

**Comment by Graur** [comment]
@includealex It's not done yet. We need to merge [this](https://github.com/objectionary/home/pull/86) PR first

**Comment by 0pdd** [comment]
@includealex the puzzle [#114](https://github.com/objectionary/eo-strings/issues/114) is still not solved.

**Comment by 0pdd** [comment]
@includealex the only puzzle [#114](https://github.com/objectionary/eo-strings/issues/114) is solved here.

**Comment by Graur** [comment]
@yegor256 Can we make another release (I suggest version `0.1.1`) ? Since this pull request merge was failed: https://github.com/objectionary/home/pull/86#issuecomment-1368049215

**Comment by yegor256** [comment]
@rultor release, tag is `0.1.1`
