### ISSUE TITLE
`regex.eo`: redundant parentheses

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/eo-strings#110]
`regex.eo` contains lots of redundant parentheses:
```java
[WARNING] Redundant parentheses (text "")
[WARNING] Redundant parentheses (text "")
[WARNING] Redundant parentheses (match txt)
```
It would be good to get rid of them.
You can check warnings by using the latest version of `eo-maven-plugin`.
Comes from: https://github.com/objectionary/eo/issues/1490

**Comment by EugeneDar** [comment]
@volodya-lombrozo @yegor256 it seems to me that this problem has already been solved. We should probably close this ticket.

**Comment by volodya-lombrozo** [comment]
@EugeneDar Indeed, I don't see such expressions anymore. Thanks.
