### ISSUE TITLE
text.is-alpha

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo-strings#128]
Let's add a method that returns `TRUE` if all chars are letters.

**Comment by Graur** [comment]
@MikhailLipanin Please, help us here

**Comment by MikhailLipanin** [comment]
@yegor256, you mean [this](https://github.com/objectionary/eo-strings/blob/master/src/main/eo/org/eolang/txt/text.eo#L363-L396) one? Or need something else

**Comment by yegor256** [comment]
@MikhailLipanin just `is-alpha` (only letters) would be great to have, in addition to `is-alphabetic` (letters and numbers)
