### ISSUE TITLE
ANTLR and violation

### ISSUE THREAD

**Issue by levBagryansky** [objectionary/eo-strings#13]
@Graur 
I have just cloned repository and added java directory:
![image](https://user-images.githubusercontent.com/32939651/184884218-8978fdaa-3590-4b11-9db8-6dede4d6cec0.png)
It returns me this;
![image](https://user-images.githubusercontent.com/32939651/184884384-469a1592-7d88-43bc-a89e-4a8768861a11.png)
So I can not find how to contribute threre.

**Comment by Graur** [comment]
@levBagryansky I'm not sure I understand the question. Just fix these violations

**Comment by Graur** [comment]
@levBagryansky This is not about ANTLR violations. it is just about code style violations in your new java files.

**Comment by levBagryansky** [comment]
@But I  just copied it from eo

**Comment by levBagryansky** [comment]
@Graur Why the same code passes in eo and does not pass here?

**Comment by Graur** [comment]
@levBagryansky because of this: https://github.com/objectionary/eo/blob/master/eo-runtime/pom.xml#L153

**Comment by levBagryansky** [comment]
@Graur Why we exluded there but don't want do the same here?

**Comment by levBagryansky** [comment]
@Graur 
What have I to do with that
![image](https://user-images.githubusercontent.com/32939651/184902608-6f8392de-df65-465f-8134-682d49313e99.png)

**Comment by Graur** [comment]
@levBagryansky You have to exclude it, like this: https://github.com/objectionary/eo/blob/master/eo-runtime/src/main/java/EOorg/package-info.java#L29

**Comment by levBagryansky** [comment]
@Graur ok, does since 0.1 mean version?

**Comment by Graur** [comment]
@levBagryansky Yes, It does

**Comment by levBagryansky** [comment]
Ok, thanks
