### ISSUE TITLE
text.repeated

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo-strings#140]
Would be great to have `.repeated` method in `text`:

```
eq.
  repeated.
    QQ.txt.text
      "foo"
    3
  "foofoofoo"
```

If the counter is less than zero, we should return an error.

See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/repeat

**Comment by yegor256** [comment]
@EugeneDar can you please help?

**Comment by yegor256** [comment]
@EugeneDar ping...

**Comment by EugeneDar** [comment]
@yegor256 I'll get to it soon

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#154](https://github.com/objectionary/eo-strings/issues/154) is still not solved.

**Comment by 0pdd** [comment]
@yegor256 the only puzzle [#154](https://github.com/objectionary/eo-strings/issues/154) is solved here.
