### ISSUE TITLE
text.chained should accept varargs

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo-strings#141]
This is what should be possible:

```
eq.
  chained.
    QQ.txt.text
      "one"
    "two"
    "three"
 "onetwothree"
```

**Comment by yegor256** [comment]
@EugeneDar can you help?

**Comment by maxonfjvipon** [comment]
@yegor256 it seems this feature is already implemented. See [this](https://github.com/objectionary/eo-strings/blob/6671dba86b676482370168a034ca132dc6c7550c/src/test/eo/org/eolang/txt/text-tests.eo#L666)

**Comment by yegor256** [comment]
@maxonfjvipon good, thanks!
