### ISSUE TITLE
eo-strings 0.2.0 contains eo-runtime library inside

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/eo-strings#147]
eo-strings 0.2.0 jar file in Maven Central contains not only eo-strings required classes, but also all classes from eo-runtime, which causes some problems during eo-runtime build.

You can check eo-strings 0.2.0 jar here:
https://repo1.maven.org/maven2/org/eolang/eo-strings/0.2.0/

**Comment by volodya-lombrozo** [comment]
The library also contains all compiled objects besides atoms

**Comment by yegor256** [comment]
@rultor release, tag is `0.3.0`

**Comment by yegor256** [comment]
@volodya-lombrozo I believe it's fixed in the latest version
