### ISSUE TITLE
`eo-collections` can't be version up in objectionaries because of `eo-strings` tests

### ISSUE THREAD

**Issue by maxonfjvipon** [objectionary/eo-strings#165]
This [build](https://github.com/objectionary/home/actions/runs/6405184948/job/17387218064?pr=183) fails because there are break changes in `eo-collections 0.10.0` related to [arguments order](https://github.com/objectionary/eo-collections/blob/0825ba8b387abf5a949e2ea54f2f4e0fcf62ca3d/src/test/eo/org/eolang/collections/list-tests.eo#L242-L245) in `list.reducedi`.

Need to change all `list.reducedi` uses in the repo, disable the tests, make new release and try to update `eo-strings` in objectionary

**Comment by 0pdd** [comment]
@maxonfjvipon the puzzle [#167](https://github.com/objectionary/eo-strings/issues/167) is still not solved.

**Comment by maxonfjvipon** [comment]
@yegor256 let's make a new release with tag `0.5.0`

**Comment by yegor256** [comment]
@rultor release, tag is `0.5.0`
