### ISSUE TITLE
text-tests.eo:32-38: Enable the tests when eo-collections...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo-strings#167]
The puzzle `165-265a52d9` from #165 has to be resolved: 

https://github.com/objectionary/eo-strings/blob/ce779af3a3f809713a8033da2abf91d6e9d5056d/src/test/eo/org/eolang/txt/text-tests.eo#L32-L38

The puzzle was created by @rultor on 05-Oct-23. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@eugenedar please pay attention to this new issue.

**Comment by EugeneDar** [comment]
@rultor, Nah.
