### ISSUE TITLE
We need compare method for text

### ISSUE THREAD

**Issue by EugeneDar** [objectionary/eo-strings#18]
We need method to compare strings in alphabetic order

**Comment by EugeneDar** [comment]
@Graur please assign me

**Comment by Graur** [comment]
@EugeneDar What is the difference between this object and `string.eq` object?

**Comment by 0pdd** [comment]
@EugeneDar the puzzle [#41](https://github.com/objectionary/eo-strings/issues/41) is still not solved.

**Comment by 0pdd** [comment]
@EugeneDar the only puzzle [#41](https://github.com/objectionary/eo-strings/issues/41) is solved here.
