### ISSUE TITLE
We need is-alphabetic method for text

### ISSUE THREAD

**Issue by EugeneDar** [objectionary/eo-strings#19]
We need have posibility to check that all signs in string are letters

**Comment by EugeneDar** [comment]
@Graur please assign me

**Comment by 0pdd** [comment]
@EugeneDar the puzzle [#48](https://github.com/objectionary/eo-strings/issues/48) is still not solved.

**Comment by 0pdd** [comment]
@EugeneDar the only puzzle [#48](https://github.com/objectionary/eo-strings/issues/48) is solved here.
