### ISSUE TITLE
We need matches-regexp method for text

### ISSUE THREAD

**Issue by EugeneDar** [objectionary/eo-strings#20]
We need to be able to check if a string matches a regexp

**Comment by Graur** [comment]
@EugeneDar What of the purpose of this object?

**Comment by EugeneDar** [comment]
@Graur this object will check that string matches a regexp and return bool value. TRUE or FALSE

**Comment by Graur** [comment]
@EugeneDar Maybe we can call it `is-regex`?

**Comment by levBagryansky** [comment]
@EugeneDar @Graur 
Why do we need this method if we already have regex.matches?

**Comment by Graur** [comment]
@levBagryansky I think that `is-regex` will work like this: 
```
regex "/(.*)/i"
.is-regex
```

**Comment by EugeneDar** [comment]
@levBagryansky you're right, we already have this functionality in regex.matches

**Comment by EugeneDar** [comment]
I'll remove this issue
