### ISSUE TITLE
We need have replaced method for text

### ISSUE THREAD

**Issue by EugeneDar** [objectionary/eo-strings#21]
We need to be able to replace some substrings in string to others

**Comment by EugeneDar** [comment]
@Graur please assign me

**Comment by Graur** [comment]
@EugeneDar Maybe `replace`? According to this: https://arxiv.org/pdf/2206.02585.pdf

**Comment by EugeneDar** [comment]
@Graur you're right

**Comment by 0pdd** [comment]
@EugeneDar the puzzle [#32](https://github.com/objectionary/eo-strings/issues/32) is still not solved.
