### ISSUE TITLE
We need have split method for text

### ISSUE THREAD

**Issue by EugeneDar** [objectionary/eo-strings#22]
We need to be able to split strings by some substrings

**Comment by EugeneDar** [comment]
@Graur please assign me

**Comment by Graur** [comment]
@EugeneDar Maybe `split`? According to this: https://arxiv.org/pdf/2206.02585.pdf

**Comment by EugeneDar** [comment]
@Graur I agree

**Comment by 0pdd** [comment]
@EugeneDar 2 puzzles [#57](https://github.com/objectionary/eo-strings/issues/57), [#58](https://github.com/objectionary/eo-strings/issues/58) are still not solved.

**Comment by 0pdd** [comment]
@EugeneDar 3 puzzles [#58](https://github.com/objectionary/eo-strings/issues/58), [#76](https://github.com/objectionary/eo-strings/issues/76), [#77](https://github.com/objectionary/eo-strings/issues/77) are still not solved; solved: [#57](https://github.com/objectionary/eo-strings/issues/57).

**Comment by 0pdd** [comment]
@EugeneDar 2 puzzles [#58](https://github.com/objectionary/eo-strings/issues/58), [#76](https://github.com/objectionary/eo-strings/issues/76) are still not solved; solved: [#57](https://github.com/objectionary/eo-strings/issues/57), [#77](https://github.com/objectionary/eo-strings/issues/77).

**Comment by 0pdd** [comment]
@EugeneDar the puzzle [#58](https://github.com/objectionary/eo-strings/issues/58) is still not solved; solved: [#57](https://github.com/objectionary/eo-strings/issues/57), [#76](https://github.com/objectionary/eo-strings/issues/76), [#77](https://github.com/objectionary/eo-strings/issues/77).

**Comment by 0pdd** [comment]
@EugeneDar the puzzle [#138](https://github.com/objectionary/eo-strings/issues/138) is still not solved; solved: [#57](https://github.com/objectionary/eo-strings/issues/57), [#58](https://github.com/objectionary/eo-strings/issues/58), [#76](https://github.com/objectionary/eo-strings/issues/76), [#77](https://github.com/objectionary/eo-strings/issues/77).
