### ISSUE TITLE
We need as-int method for text

### ISSUE THREAD

**Issue by EugeneDar** [objectionary/eo-strings#23]
We need to be able to cast string to int

**Comment by EugeneDar** [comment]
@Graur please assign me

**Comment by Graur** [comment]
@EugeneDar Do you mean `text` object?

**Comment by EugeneDar** [comment]
@Graur you're right

**Comment by levBagryansky** [comment]
@Graur can I do that?
please assign me

**Comment by EugeneDar** [comment]
I don't mind.

**Comment by Graur** [comment]
@levBagryansky Go ahead

**Comment by levBagryansky** [comment]
@Graur why do we write `Ctor` in the docs comments, like here?:
    /**
     * Ctor.
     *
     * @param sigma Sigma
     */

**Comment by levBagryansky** [comment]
@Graur done

**Comment by Graur** [comment]
@levBagryansky I am not the author of this issue

**Comment by levBagryansky** [comment]
@EugeneDar done

**Comment by EugeneDar** [comment]
@levBagryansky thanks
