### ISSUE TITLE
eo-strings release with `0.0.1` version

### ISSUE THREAD

**Issue by Graur** [objectionary/eo-strings#35]
We need to release `eo-strings`, after applying this PR: https://github.com/objectionary/eo-strings/pull/34

**Comment by Graur** [comment]
@yegor256 @EugeneDar can you help with this?

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.1`

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.2`

**Comment by yegor256** [comment]
@Graur done

**Comment by Graur** [comment]
@yegor256 Thanks!
