### ISSUE TITLE
take last byte in "%c"

### ISSUE THREAD

**Issue by IngeniariusSoftware** [objectionary/eo-strings#40]
It is possible to use the last byte when printing char?
It will require less extra code and work more logically, like the number mod 255

current realization if I want to print character with code 100:

```java
QQ.txt.sprintf "%c\n" (100.as-bytes.slice 7 1)
```

will be:

```java
QQ.txt.sprintf "%c\n" (100.as-bytes)
```

**Comment by mximp** [comment]
@yasamprom is this solved?

**Comment by mximp** [comment]
@Graur Is this solved?

**Comment by Graur** [comment]
@mximp Looks like solved
@IngeniariusSoftware Can we close this issue?

**Comment by IngeniariusSoftware** [comment]
@Graur, yes, thanks!
