### ISSUE TITLE
EOtext$EOcompare.java:55-57: Current implementation using...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo-strings#41]
The puzzle `18-c333659d` from #18 has to be resolved: 

https://github.com/objectionary/eo-strings/blob/10f9f4104f032052aa97ac5b441f13f163fabbe5/src/main/java/EOorg/EOeolang/EOtxt/EOtext$EOcompare.java#L55-L57

The puzzle was created by @EugeneDar on 07-Sep-22. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@eugenedar please pay attention to this new issue.

**Comment by EugeneDar** [comment]
@Graur please assign it to me.

**Comment by Graur** [comment]
@EugeneDar sure, go ahead

**Comment by 0pdd** [comment]
The puzzle `18-c333659d` has disappeared from the source code, that's why I closed this issue. //cc @eugenedar
