### ISSUE TITLE
text.eo:31-34: Current version use incorrect names for...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo-strings#57]
The puzzle `22-fbf67ffc` from #22 has to be resolved: 

https://github.com/objectionary/eo-strings/blob/018670f88ecbf9c56632af223fc387883c050ec8/src/main/eo/org/eolang/txt/text.eo#L31-L34

The puzzle was created by @rultor on 09-Sep-22. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@eugenedar please pay attention to this new issue.

**Comment by EugeneDar** [comment]
https://github.com/objectionary/on-the-origin-of-objects/issues/15

**Comment by EugeneDar** [comment]
@Graur please assign it to me.

**Comment by Graur** [comment]
@EugeneDar sure, go ahead

**Comment by 0pdd** [comment]
The puzzle `22-fbf67ffc` has disappeared from the source code, that's why I closed this issue. //cc @eugenedar

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#76](https://github.com/objectionary/eo-strings/issues/76), [#77](https://github.com/objectionary/eo-strings/issues/77) are still not solved.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#76](https://github.com/objectionary/eo-strings/issues/76) is still not solved; solved: [#77](https://github.com/objectionary/eo-strings/issues/77).

**Comment by 0pdd** [comment]
@0pdd all 2 puzzles are solved here: [#76](https://github.com/objectionary/eo-strings/issues/76), [#77](https://github.com/objectionary/eo-strings/issues/77).
