### ISSUE TITLE
some methods must return text instead of string

### ISSUE THREAD

**Issue by levBagryansky** [objectionary/eo-strings#64]
@Graur @EugeneDar 
I think `text.trim`, `text.lower-case` and `text.upper-case` have to return `text` because they are `text` attributes. The situation is similar to attributes of `list` that return `list` instead of `array`.
What do you think?

**Comment by EugeneDar** [comment]
@levBagryansky I agree.

**Comment by levBagryansky** [comment]
@Graur I would  like to do that

**Comment by Graur** [comment]
@levBagryansky Sure, go ahead
