### ISSUE TITLE
We need to update the version

### ISSUE THREAD

**Issue by EugeneDar** [objectionary/eo-strings#67]
As we implemented whole list of text methods which we wanted, we should release new version.

**Comment by EugeneDar** [comment]
@Graur @yegor256 what do you think?

**Comment by Graur** [comment]
@EugeneDar I agree. What version do you suggest?

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.4`

**Comment by Graur** [comment]
@yegor256 Thanks!
