### ISSUE TITLE
text.eo:96-98: Current implementation works only with...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo-strings#79]
The puzzle `65-bbad65b3` from #65 has to be resolved: 

https://github.com/objectionary/eo-strings/blob/c72987dff181aad56c1c05b519e7d502c516eef0/src/main/eo/org/eolang/txt/text.eo#L96-L98

The puzzle was created by @rultor on 28-Sep-22. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@eugenedar please pay attention to this new issue.

**Comment by levBagryansky** [comment]
@EugeneDar I can do it

**Comment by 0pdd** [comment]
The puzzle `65-bbad65b3` has disappeared from the source code, that's why I closed this issue. //cc @eugenedar
