### ISSUE TITLE
to move `sprintf` object from eo-runtime of EO

### ISSUE THREAD

**Issue by Graur** [objectionary/eo-strings#8]
We need to move `sprintf` object from `eo-runtime` of EO

**Comment by Graur** [comment]
@mnj2kk Please, help us here

**Comment by Graur** [comment]
@levBagryansky Maybe you can help us here?

**Comment by levBagryansky** [comment]
@Graur done

**Comment by Graur** [comment]
@levBagryansky Thanks!
